### ISSUE TITLE
Timestamp 0 in result file

### ISSUE THREAD

**Issue by octaviand2** [tilln/jmeter-sshmon#5] opened 2020-08-27 06:34 UTC
Hello,

when running a test with SSHMon collecting resource utilization data, the resulting CSV is fine when running in GUI mode. However, in non-GUI mode the timestamp column's value is 0 for all the entries.

Can you please support?

Thanks
Octavian.

**Comment by octaviand2** [comment] 2020-08-27 06:35
There is also this output in the console, but nothing else in the jmeter.log

The JVM should have exited but did not.
The following non-daemon threads are still running (DestroyJavaVM is OK):
Thread[DestroyJavaVM,5,main], stackTrace:
Thread[Thread-4,5,main], stackTrace:java.lang.Thread#sleep
nz.co.breakpoint.jmeter.vizualizers.sshmon.SSHMonSampler#generateSamples at line:83
kg.apc.jmeter.vizualizers.MonitoringResultsCollector#processConnectors at line:215
kg.apc.jmeter.vizualizers.MonitoringResultsCollector#run at line:122
java.lang.Thread#run at line:844

**Comment by tilln** [comment] 2020-08-27 22:35
Hi @octaviand2 
Can you please provide 
- your output CSV files, 
- your script, 
- the full jmeter log file, 
- the command line you start it with

 so I can analyse what is going on, as I can't reproduce that behaviour.

**Comment by octaviand2** [comment] 2020-08-28 05:39
Hi Till,

thanks a lot for getting in touch.
After further investigation, I came to the conclusion that if I run jmeter
with -p properties file, the timestamp is zero. No clue why is that.

I am sending attached the sample script, outputs, properties file.

It works fine if I start without -p:

./jmeter -n -t
/Users/octaviandobrin/nokia_git/vz-hss/src/main/jmx/ssh_monitor.jmx

And not ok if I start with -p:

./jmeter -n -t
/Users/octaviandobrin/nokia_git/vz-hss/src/main/jmx/ssh_monitor.jmx -p
/Users/octaviandobrin/nokia_git/vz-hss/src/main/configuration/test_ssh_mon.properties

Thanks for your support.
With Regards
Octavian.

**Comment by tilln** [comment] 2020-08-28 05:43
I don't think you can send attachments to that Github issue email. I suggest adding them in the Github web UI.

Great that you have narrowed it down.
What's the content of your properties file? That may be key to a solution.

**Comment by octaviand2** [comment] 2020-08-28 05:48
Hi,

can you please share a link? Alternatively you can download them from here:
https://1drv.ms/u/s!Ai05zSJI5V1BifoJfWLrIj78ZEBa-A?e=sw6HZz

Also, the property file is very basic (I just left prop1=10 in it)

Thanks and Regards
Octavian

**Comment by tilln** [comment] 2020-08-28 06:03
Thanks, I can access those.
I can also reproduce the zero timestamps with my own script.
I'll have to do some investigation where the root cause is: could be JMeter, the JMeter plugins [base class](https://github.com/undera/jmeter-plugins/blob/master/infra/common/src/main/java/kg/apc/jmeter/vizualizers/MonitoringResultsCollector.java) or this plugin.

Meanwhile I suggest as a work-around to start with command line option `-q` rather than `-p`. This resolved it for me.

**Comment by tilln** [comment] 2020-08-28 06:53
When the properties file is passed in via command line option `-p` (rathen than `-q`), in GUI or non-GUI mode, the [default value](https://jmeter.apache.org/usermanual/listeners.html#defaults) of the JMeter property `sampleresult.timestamp.start=true` is *not* set, but it is treated as false, which means that the result file will not contain the sample *start* times but the *end* times.
The end times however, are not assigned properly but default to the 0 value reported here.

When the [collector](https://github.com/undera/jmeter-plugins/blob/c8bf66d3f6742d7391764890cf110faae597b4fd/infra/common/src/main/java/kg/apc/jmeter/vizualizers/MonitoringResultsCollector.java#L239) creates a [`MonitoringSampleResult`](https://github.com/undera/jmeter-plugins/blob/c8bf66d3f6742d7391764890cf110faae597b4fd/infra/common/src/main/java/kg/apc/jmeter/vizualizers/MonitoringSampleResult.java#L16), the end time is not assigned.

The same issue is present for other, similar Listeners, such as [JXMMon](https://github.com/undera/jmeter-plugins/blob/c8bf66d3f6742d7391764890cf110faae597b4fd/plugins/jmxmon/src/main/java/kg/apc/jmeter/jmxmon/JMXMonSampleResult.java#L16) and [DBMon](https://github.com/undera/jmeter-plugins/blob/c8bf66d3f6742d7391764890cf110faae597b4fd/plugins/dbmon/src/main/java/kg/apc/jmeter/dbmon/DbMonSampleResult.java#L16), but not [Perfmon](https://github.com/undera/jmeter-plugins/blob/c8bf66d3f6742d7391764890cf110faae597b4fd/plugins/perfmon/src/main/java/kg/apc/jmeter/perfmon/PerfMonSampleResult.java#L16).

So, this issue should be raised for the [owning repo](https://github.com/undera/jmeter-plugins/) (via [Google Groups](http://groups.google.com/group/jmeter-plugins)). 
Therefore closing this.

**Closed by tilln** 2020-08-28 06:53 UTC

**Comment by octaviand2** [comment] 2020-08-28 07:48
Thanks a lot, running with -q works; as well as by
adding sampleresult.timestamp.start=true in the properties file.

**Comment by tilln** [comment] 2020-08-29 03:25
Fix available in [1.3-SNAPSHOT](https://github.com/tilln/jmeter-sshmon/releases/tag/1.3-SNAPSHOT)

**Comment by octaviand2** [comment] 2020-09-29 07:01
Hi Till,

a quick question -if that is ok with you.
Can I setup sshmon in such a way that it collects resource utilization only
if certain criteria is met? For example, I want to collect only when
running on server/non-gui and not local and tried the setup below, but it
is not working (e.g it still tries to connect and collect data as far as I
can see).

Thanks and Regards
Octavian.

[image: image.png]

**Comment by tilln** [comment] 2020-09-30 00:27
Hi @octaviand2 

Please provide more details of your setup that is not working.

**Comment by octaviand2** [comment] 2020-09-30 06:39
Hi Till,

I want to be able to collect resource utilization differently based on some
system properties. To be more specific, I want to connect to localhost and
port 9500 when running from GUI and 10.1.1.1 and port 22 when running
server mode.

I cannot use a property for port - for example ${__P(port,10)} (it seems
the field only accepts numeric values); therefore I tried to put the SSHMon
inside an if controller hoping it will only establish ssh sessions and
collect under certain conditions. But that doesn't work as well.

Can you please advise?

Thanks and Regards
Octavian.

**Comment by tilln** [comment] 2020-09-30 07:15
@octaviand2  you're quite right, that's not working.
I've created #7.
Fix available in [1.3-SNAPSHOT](https://github.com/tilln/jmeter-sshmon/releases/tag/1.3-SNAPSHOT)

**Comment by octaviand2** [comment] 2020-09-30 11:30
Hi Till,

I downloaded 1.3 and replaced the JAR, still the port does not accept
non-numeric data (e.g. ${__P(port,22)}. Can you please advise?

Thanks and Regards
Octavian.

**Comment by tilln** [comment] 2020-09-30 21:02
Hi @octaviand2 

Please start JMeter in with `-LDEBUG` and upload the jmeter.log file here.

**Comment by octaviand2** [comment] 2020-10-06 08:01
Hi Till,

it works fine - e.g. I can enter alphanumeric there (e.g. ${__P function)
and the value is retrieved.

Do you have an estimate when you will make it in a formal release to be
installed with plugins manager?

Thanks and Regards
Octavian.

**Comment by tilln** [comment] 2020-10-06 22:11
Hi @octaviand2 

Thanks for reporting back and confirming.

No estimate yet, as I would like to include a fix for another issue that's been discussed [here](https://groups.google.com/g/jmeter-plugins/c/5g2JqivexXE), and that needs some more investigation.

**Comment by octaviand2** [comment] 2020-11-24 14:18
Hi Till,

any updates on the new formal release date?

With Regards
Octavian.

**Comment by tilln** [comment] 2020-11-24 22:03
Hi @octaviand2,

For the next release, a new feature has been implemented [(jump host support)](https://github.com/tilln/jmeter-sshmon/blob/e44989f24496ef997d284a6df8a663b33e253ea9/README.md#jump-hosts-since-v13) which depends on features in the Apache Mina SSHD library, so as soon as they release v2.6.0 the new version of this plugin gets released.

**Comment by octaviand2** [comment] 2021-02-17 10:41
Hi Till,

any chance you could consider adding an "enable" flag to the SSH Mon
sampler?

The scenario I have is to be able to specify, using an JMeter properties,
if during a test the SSHMon sampler should or should not collect data (e.g.
SSHMon sampler to "accept" a configuration from
${__P(collect_resource_util_data,true)}

The only solution I see is to modify the jmx with enabled=false, but I want
to avoid that.

Thanks and Regards
Octavian.

**Comment by tilln** [comment] 2021-02-17 20:17
Hi @octaviand2 

Unfortunately that wouldn't be easy, as this plugin is based on JMeter-Plugins Common [components](https://github.com/tilln/jmeter-sshmon/blob/1.3/pom.xml#L132-L134), namely [`AbstractMonitoringVisualizer`](https://github.com/undera/jmeter-plugins/blob/master/infra/common/src/main/java/kg/apc/jmeter/graphs/AbstractMonitoringVisualizer.java).
You could consider submitting a pull request there.
